
language: node_js
dist: trusty
node_js:
  - "9"
install:
  - npm install
script:
  - hexo clean
  - hexo g
  - chmod +x ./deploy.sh
  - \cp -f CNAME public/CNAME
  - cd ./public
  - git init
  - git config --global push.default matching
  - git config --global user.email "${GitHubEMail}"
  - git config --global user.name "aiokr"
  - git add --all .
  - git commit -m "Auto Builder of ${GitHubUser}'s blog"
  - git push --force --quiet \"https://aiokr:${GitHubKEY}@github.com/aiokr/hexo-page.git" master:master
  
cache:
  directories:
    - node_modules